services:
  vulcanosDB:
    image: mongo:5.0.0
    container_name: vulcanos-database
    volumes:
      - ./mongo/:/data/db/
    ports:
      - 27017:27017
  vulcanosBackend:
    image: vulcanos-backend
    container_name: vulcanos-backend-service
    ports:
      - 8000:8000
